source 'https://rubygems.org'

# Project requirements
gem 'rake'

# Component requirements
gem 'omniauth'
gem 'omniauth-twitter'
gem 'factory_girl'
gem 'forgery'
gem 'database_cleaner'
gem 'compass'
gem 'haml'
gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'mysql2'

# Test requirements
gem 'rspec', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'

# Padrino Stable Gem
gem 'padrino', '0.11.4'

